import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";
import { ModeToggle } from "@/components/ModeToggle";

const centuryGothic = localFont({
  src: "./fonts/CenturyGothic.woff",
  variable: "--font-century-gothic",
});

const centuryGothicItalic = localFont({
  src: "./fonts/CenturyGothic-Italic.woff",
  variable: "--font-century-gothic-italic",
});

const centuryGothicBold = localFont({
  src: "./fonts/CenturyGothic-Bold.woff",
  variable: "--font-century-gothic-bold",
});

const centuryGothicBoldItalic = localFont({
  src: "./fonts/CenturyGothic-BoldItalic.woff",
  variable: "--font-century-gothic-bold-italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${centuryGothic.className} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ModeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}

export {
  centuryGothic,
  centuryGothicItalic,
  centuryGothicBold,
  centuryGothicBoldItalic,
};
