export const steps = [
  { title: "Basic Information", fields: ["name", "industry"] },
  { title: "Target Audience", fields: ["targetAudience"] },
  { title: "Goals", fields: ["goals"] },
  { title: "Budget & Timeline", fields: ["budget", "timeline"] },
];

export const initialBusinesses = [
  {
    id: 1,
    name: "Tech Startup",
    industry: "Technology",
    targetAudience: "Small Businesses",
    goals: "Increase market share by 20%",
    createdAt: "2023-01-15T00:00:00Z",
  },
  {
    id: 2,
    name: "E-commerce Store",
    industry: "Retail",
    targetAudience: "Young Adults",
    goals: "Expand to 3 new cities",
    createdAt: "2023-02-20T00:00:00Z",
  },
  {
    id: 3,
    name: "Local Restaurant",
    industry: "Food & Beverage",
    targetAudience: "Families",
    goals: "Increase online orders by 30%",
    createdAt: "2023-03-10T00:00:00Z",
  },
  {
    id: 4,
    name: "Fitness Gym",
    industry: "Health & Wellness",
    targetAudience: "Fitness Enthusiasts",
    goals: "Launch new fitness program",
    createdAt: "2023-04-05T00:00:00Z",
  },
  {
    id: 5,
    name: "Digital Marketing Agency",
    industry: "Marketing",
    targetAudience: "Startups",
    goals: "Grow social media following by 50%",
    createdAt: "2023-05-12T00:00:00Z",
  },
  {
    id: 6,
    name: "Web Development Company",
    industry: "Technology",
    targetAudience: "Small Businesses",
    goals: "Launch new website for client",
    createdAt: "2023-06-25T00:00:00Z",
  },
  {
    id: 7,
    name: "Mobile App Startup",
    industry: "Technology",
    targetAudience: "Young Adults",
    goals: "Reach 1 million downloads",
    createdAt: "2023-07-30T00:00:00Z",
  },
  {
    id: 8,
    name: "Fashion Boutique",
    industry: "Retail",
    targetAudience: "Young Adults",
    goals: "Launch new clothing line",
    createdAt: "2023-08-18T00:00:00Z",
  },
];
